### PR TITLE
Decode performance boost 2

### PR DESCRIPTION
**Pull request by tonyarkles**
This is a follow-up to #14 . Squeezed a bit more performance out of it.

### CODE REVIEW

**Comment by denvaar** [comment]
totally cool, thanks @tonyarkles

**Comment by denvaar** [comment]
@tonyarkles this breaks tests.

**Comment by tonyarkles** [comment]
Oh, dang, I’ll take a look in the morning.

**Comment by denvaar** [comment]
It's fine, I took care of it. Thanks for the contribution

**Pull request merged**
